Added q/escape shortcuts to quit the current lua app.
paxo-phone/PaxOS-9 pull request #71
Opened 2024-05-21 16:29 UTC by b5i

2024-05-21 20:19 UTC, Charlito33 requested changes
Vaudrait pas plutôt le mettre dans ``hardware::getHomeButton()`` ?
Ce serait plus logique (et plus simple)

2024-05-22 20:17 UTC, Charlito33 approved these changes

2024-05-22 20:24 UTC, merged

2024-05-22 20:28 UTC, Charlito33 commented
C'est merge, mais par contre j'avais pas vu que c'était sur la branch [paxo-phone:gabriel_dev](https://github.com/paxo-phone/PaxOS-9/tree/gabriel_dev) et pas [paxo-phone:main](https://github.com/paxo-phone/PaxOS-9/tree/main).

2024-05-22 20:51 UTC, b5i commented
Pas de soucis c'était voulu, de base ça devait servir à debugger la leak de lua.