App Horloge et GuiManager
paxo-phone/PaxOS-9 pull request #88
Opened 2024-07-31 21:47 UTC by pymuzard

Ajout du GuiManager
catch des exceptions des app Lua
ajout d'une lite pour les app de l'écran d'accueil
ajout de l'app Horloge

2024-08-08 15:18 UTC, paxo-project requested changes
Quelques trucs a corriger mais cette PR apporte pas mal de trucs!
merci beaucoup :)

2024-08-08 15:18 UTC, paxo-project commented on lib/gsm/src/gsm.cpp
> +        eventHandlerBack.setInterval(&GSM::getHour, 1000);
Sur esp ça va surcharger le port GSM, donc il faut garder 5 s

2024-08-08 15:18 UTC, paxo-project commented on lib/gui/src/elements/Switch.cpp
> +            m_surface->fillRoundRect(0, 0, m_width, m_height, 10, COLOR_GREY);
C'est pas ce qu'on avait prévu sur le design, c'est vraiment mieux ?

2024-08-08 15:18 UTC, paxo-project commented on lib/graphics/src/PaxOS-9-1.code-workspace
ajouter au git ignore

2024-08-08 15:18 UTC, paxo-project commented on lib/gsm/src/gsm.cpp
Le niveau de batterie est pas linéaire sur des batteries au lithium

2024-08-08 20:33 UTC, pymuzard commented on lib/gui/src/elements/Switch.cpp
> +            m_surface->fillRoundRect(0, 0, m_width, m_height, 10, COLOR_GREY);
ca me parait plus pertinent (pas actif: gris, actif: noir)
mais ca reste une suggestion

2024-08-08 20:34 UTC, pymuzard commented on lib/gsm/src/gsm.cpp
ok, on verra ca plus tard, no worries

2024-08-08 20:41 UTC, pymuzard commented on lib/gsm/src/gsm.cpp
> +        eventHandlerBack.setInterval(&GSM::getHour, 1000);
ok, mais du coup l'heure n'est rafraîchi que toutes les 5 Secondes sur l'ESP ?
si c'est le cas, je dois revoir l'app horloge car je mets à jour l'heure toutes les secondes (avec l'aiguille rouge)

2024-08-09 06:34 UTC, paxo-rch commented
Je pense qu'il y a moyen d'utiliser le millis (nb ms depuis le démarrage)
pour calculer et prédire plus précisément

Le jeu. 8 août 2024, 22:41, pymuzard ***@***.***> a écrit :

> ***@***.**** commented on this pull request.
> ------------------------------
>
> In lib/gsm/src/gsm.cpp
> <https://github.com/paxo-phone/PaxOS-9/pull/88#discussion_r1710269268>:
>
> >
>          updateHour();
>          getNetworkQuality();
>
> -        eventHandlerBack.setInterval(&GSM::getHour, 5000);
> +        // Mise à jour de l'heure toutes les 1000 ms
> +        eventHandlerBack.setInterval(&GSM::getHour, 1000);
>
> ok, mais du coup l'heure n'est rafraîchi que toutes les 5 Secondes sur
> l'ESP ?
> si c'est le cas, je dois revoir l'app horloge car je mets à jour l'heure
> toutes les secondes (avec l'aiguille rouge)
>
> —
> Reply to this email directly, view it on GitHub
> <https://github.com/paxo-phone/PaxOS-9/pull/88#discussion_r1710269268>,
> or unsubscribe
> <https://github.com/notifications/unsubscribe-auth/ASV6YE3GEZPA43GAHZHRSFDZQPJXJAVCNFSM6AAAAABLZJZWXCVHI2DSMVQWIX3LMV43YUDVNRWFEZLROVSXG5CSMV3GSZLXHMZDEMRYHAZDSMZRG4>
> .
> You are receiving this because your review was requested.Message ID:
> ***@***.***>
>

2024-08-11 18:04 UTC, closed without merging