Merge Main et ajout minuteur à l'app Horloge
paxo-phone/PaxOS-9 pull request #89
Opened 2024-08-11 16:28 UTC by pymuzard

Merge avec le Main
Ajout fonctionnalité minuteur sur l'app Horloge
retour arrière sur la le calcul du niveau de batterie
Ajout niveau de criticité sur les affichage de messages (GuiManager)

2024-08-11 18:06 UTC, b5i requested changes

2024-08-11 18:06 UTC, b5i commented on lib/graphics/src/PaxOS-9-1.code-workspace
Il faudrait probablement enlever ce fichier.

2024-08-11 18:15 UTC, b5i commented on storage/apps/horloge/app.lua
> +    vListHeure = gui:vlist(minuteur, 55, 10, 50, 250)
Ton composant de sélection d'heure/minutes etc... est top, je pense qu'on pourrait même le move directement comme un élément de l'os.

2024-08-13 18:25 UTC, b5i commented on lib/gsm/src/gsm.cpp
> +        // Mise à jour de l'heure toutes les 1000 ms
plutôt toutes les 5000ms non?

2024-08-13 18:25 UTC, b5i commented on lib/gui/src/GuiManager.cpp
> +        int GuiManager::showMessage(WINDOW_TYPE type, const std::string& msg ) {
Pourquoi ça retourne un int si de toute façon c'est 1?

2024-08-13 18:35 UTC, merged

2024-08-14 08:26 UTC, pymuzard commented on lib/gui/src/GuiManager.cpp
> +        int GuiManager::showMessage(WINDOW_TYPE type, const std::string& msg ) {
je voulais me laisser la place de le faire évoluer en gérant éventuellement des boutons (par exemple, un message de confirmation avec un bouton OK ou CANCEL)

2024-08-14 08:29 UTC, pymuzard commented on lib/gsm/src/gsm.cpp
> +        // Mise à jour de l'heure toutes les 1000 ms
yes c'est ce qu'à dit Gabriel. je l'avait mis à 1000 pour gérer le rafraichissement de l'horloge toutes les secondes... mais si trop lourd je verrais dans l'appli pour "estimer" les secondes (sur base de millis() )
Après, preneur de votre retour de l'appli Horloge sur le Lao (je bosse sur l'émulateur pour le moment... donc est-ce que ca joue vraiment sur le rafraichissement ou pas ?)